<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <NuclearOptionDir Condition="'$(NuclearOptionDir)' == ''">$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..'))</NuclearOptionDir>
    <BaseIntermediateOutputPath>obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>obj\$(MSBuildProjectName)\</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>
