<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <AssemblyName>HorusMod</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <Reference Include="BepInEx">
      <HintPath>$(NuclearOptionDir)\BepInEx\core\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(NuclearOptionDir)\BepInEx\core\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Rewired_Core">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\Rewired_Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\UnityEngine.JSONSerializeModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <Reference Include="Mirage">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\Mirage.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if not exist &quot;$(ProjectDir)..\BepInEx\plugins\HorusMod&quot; mkdir &quot;$(ProjectDir)..\BepInEx\plugins\HorusMod&quot;&#xD;&#xA;if exist &quot;$(ProjectDir)..\BepInEx\plugins\HorusMod\$(TargetFileName).old&quot; del /F /Q &quot;$(ProjectDir)..\BepInEx\plugins\HorusMod\$(TargetFileName).old&quot;&#xD;&#xA;if exist &quot;$(ProjectDir)..\BepInEx\plugins\HorusMod\$(TargetFileName)&quot; move /Y &quot;$(ProjectDir)..\BepInEx\plugins\HorusMod\$(TargetFileName)&quot; &quot;$(ProjectDir)..\BepInEx\plugins\HorusMod\$(TargetFileName).old&quot;&#xD;&#xA;copy /Y &quot;$(TargetPath)&quot; &quot;$(ProjectDir)..\BepInEx\plugins\HorusMod\$(TargetFileName)&quot;" />
  </Target>

</Project>
